# Triggered one-time refresh.
import json, csv, re
from datetime import datetime
from pathlib import Path
P=Path('opportunities.json'); jobs=json.loads(P.read_text(encoding='utf-8'))
def norm(s): return re.sub(r'[^a-z0-9]+',' ',str(s or '').lower()).strip()
def d(s):
    try:return datetime.strptime(s,'%B %d, %Y')
    except:return datetime.min
remove={('GE Vernova','GE Vernova Digital Technology Internship - Summer 2027'),('Arboreal Management','Software Engineering Intern'),('Melaleuca: The Wellness Company','Internship Summer 2027 - Cybersecurity')}; jobs=[j for j in jobs if (j.get('company'),j.get('role')) not in remove]
for j in jobs:
    if j.get('company')=='Washington National Insurance Company' and 'Cyber Security IT Intern' in j.get('role',''): j.update({'company':'CNO Financial Group','location':'United States','work':'Remote','application_url':'https://careers.cnoinc.com/carmel-in/cyber-security-it-intern-remote/08EF775A045D4EFE9CEC1D57D0B83B2C/job/','job_id':'JR170419','description':'Paid cybersecurity internship rotating across Security Operations, Engineering, and Governance.','qualifications':"Progress toward a bachelor's degree in CS, IT, or related field; rising junior/senior; expected graduation Dec. 2027-June 2029; 40 hours/week for 10-12 weeks.",'notes':'May 17-August 6, 2027. Fully remote in the U.S.; Central/Eastern Time preferred. No visa sponsorship.','source':'Employer'})
    if j.get('company')=='Rockefeller Capital Management' and 'Information Security' in j.get('role',''): j.update({'location':'New York, NY','work':'In person','hourly_rate':'$38/hour','total_compensation':'$15,200','application_url':'https://careers.rockco.com/careers-home/jobs/5355?lang=en-us','job_id':'5355','description':'Ten-week Information Security summer analyst role supporting security controls, threat defenses, policies, risk reduction, awareness, metrics, and security tools.','qualifications':'Projected 2028 graduate in good standing; cybersecurity, computer science, economics, psychology, mathematics, or data concentration desirable.','notes':'10-week June-August program. Employer-posted rate is $38/hour.','source':'Employer'})
new=[
{'company':'IBM','role':'X-Force Red Hacker Intern 2027','location':'Austin, TX','work':'In person','open_date':'August 14, 2026','close_date':'Rolling','hourly_rate':'Est. $24.92-$45.69/hour','total_compensation':'$51,840-$95,040/year (annualized)','application_url':'https://www.ibm.com/careers/search','job_id':'129253','description':'Offensive-security internship supporting live client penetration-testing engagements.','qualifications':'University student; security knowledge preferred; onsite Austin May-August 2027; no current/future visa sponsorship.','notes':'Employer projected annualized salary range $51,840-$95,040.','source':'Employer'},
{'company':'Interactive Brokers','role':'Cybersecurity Internship 2027','location':'Greenwich, CT','work':'In person','open_date':'August 13, 2026','close_date':'March 1, 2027','hourly_rate':'Undisclosed','total_compensation':'Undisclosed','application_url':'https://www.interactivebrokers.com/en/general/about/careers.php','job_id':'642','description':'Nine-week onsite cybersecurity internship covering security engineering, assessments, scanning, threat monitoring, penetration testing, red teaming, and AI testing.','qualifications':'Cybersecurity/CS-related degree; Dec. 2027-May 2028 graduation preferred; minimum GPA 3.5.','notes':'9-week onsite program. Deadline March 1.','source':'Employer'},
{'company':'BDO USA','role':'Assurance Intern, Technology Risk Assurance - Summer 2027 (Atlanta)','location':'Atlanta, GA','work':'In person','open_date':'July 10, 2026','close_date':'September 17, 2026','hourly_rate':'Undisclosed','total_compensation':'Undisclosed','application_url':'https://www.linkedin.com/jobs/view/4363237476','job_id':'11429','description':'Technology Risk Assurance internship supporting application/control testing, IT audit, SOX reviews, walkthroughs, workpapers, and reporting.','qualifications':'Pursuing accounting, computer science, or information systems degree.','notes':'Apply before September 17, 2026.','source':'Employer'},
{'company':'Marathon Petroleum','role':'Intern/Co-op - Information Technology (Summer 2027)','location':'Findlay, OH / San Antonio, TX','work':'In person','open_date':'August 14, 2026','close_date':'August 16, 2026','hourly_rate':'$24.95-$31.19/hour','total_compensation':'Undisclosed','application_url':'https://mpc.wd1.myworkdayjobs.com/en-US/MPCCareers?q=00023241','job_id':'00023241','description':'IT internship with possible placements in systems analysis, cloud, cybersecurity, infrastructure, software engineering, and QA.','qualifications':'Related IT/CS/engineering major; strong academics; indefinite U.S. work authorization without sponsorship; must remain enrolled.','notes':'Employer-posted pay $24.95-$31.19/hour.','source':'Employer'},
{'company':'TikTok','role':'Search Security Strategy Operations Intern (TikTok-Platform Responsibility-Search) - 2027 Summer','location':'San Jose, CA','work':'In person','open_date':'August 14, 2026','close_date':'Rolling','hourly_rate':'$25/hour','total_compensation':'Undisclosed','application_url':'https://lifeattiktok.com/search/','job_id':'A145452','description':'Search-security strategy internship focused on content safety, detection, intervention, emergency response, large models, and security platforms.','qualifications':"Undergraduate/master's student in CS, statistics, information management, data science, or related field.",'notes':'Rolling applications. Employer-posted rate $25/hour.','source':'Employer'},
{'company':'ByteDance','role':'Security Software Engineer Project Intern (Network Security) - 2026 Start (BS/MS)','location':'San Jose, CA','work':'In person','open_date':'August 14, 2026','close_date':'Rolling','hourly_rate':'$45-$60/hour','total_compensation':'Undisclosed','application_url':'https://joinbytedance.com/search/','job_id':'A177024A','description':'Network-security project internship improving WAF intelligence against HTTP floods, malicious bots, and evasive activity.','qualifications':'Undergraduate/postgraduate STEM student; security fundamentals and a programming/scripting language.','notes':'At least 3 months. Rolling applications. Employer-posted rate $45-$60/hour.','source':'Employer'}]
ids={str(j.get('job_id','')) for j in jobs if j.get('job_id')}; keys={(norm(j.get('company')),norm(j.get('role'))) for j in jobs}
for j in new:
    if str(j.get('job_id','')) not in ids and (norm(j['company']),norm(j['role'])) not in keys: jobs.append(j)
jobs.sort(key=lambda j:(str(j.get('company','')).lower(),str(j.get('role','')).lower())); jobs.sort(key=lambda j:d(j.get('open_date','')),reverse=True)
P.write_text(json.dumps(jobs,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
h=['company','role','location','work','open_date','close_date','hourly_rate','total_compensation','application_url','linkedin_url','job_id','employment_type','description','qualifications','responsibilities','notes']
with open('opportunities.csv','w',encoding='utf-8',newline='') as f:
 w=csv.DictWriter(f,fieldnames=h,extrasaction='ignore');w.writeheader();[w.writerow({x:j.get(x,'') for x in h}) for j in jobs]
def c(v):return str(v or '').replace('|','\\|').replace('\n',' ').strip()
l=['# Summer 2027 U.S. CS, Cybersecurity, IT & Early-Career Opportunities','','**Updated:** August 14, 2026  ',f'**Unique roles:** {len(jobs)}  ',f'**Internships:** {len(jobs)}  ','**Post-grad / early-career:** 0','','Click a job title to open its application page. Listings are automatically deduplicated and sorted newest to oldest.','','| Company | Opportunity | Type | Location | Work | Open date | Close date | Hourly rate | Estimated total compensation |','|---|---|---|---|---|---|---|---|---|']
for j in jobs:
 r=c(j.get('role'));u=str(j.get('application_url','')).strip();a=f'[{r}]({u})' if u else r;l.append(f"| {c(j.get('company'))} | {a} | Internship | {c(j.get('location'))} | {c(j.get('work'))} | {c(j.get('open_date'))} | {c(j.get('close_date'))} | {c(j.get('hourly_rate') or 'Undisclosed')} | {c(j.get('total_compensation') or 'Undisclosed')} |")
l+=['','## Data notes','','- `Rolling` means no fixed closing date was published.','- `Undisclosed` means compensation was not published.','- Values marked `Est.` are conversions or clearly labeled estimates.','','## Sortable tracker','','Enable GitHub Pages through **Settings → Pages → Deploy from a branch → main → /(root)**.']
Path('README.md').write_text('\n'.join(l)+'\n',encoding='utf-8');print('Updated',len(jobs),'roles')